# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='todolist',
        ),
        migrations.RemoveField(
            model_name='todoitem',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='todo_item',
            field=models.ManyToManyField(blank=True, related_name='items_card', to='todo.TodoItem'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='card',
            field=models.ManyToManyField(blank=True, related_name='card_list', to='todo.Card'),
        ),
    ]
