# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20160814_0151'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ['card_name']},
        ),
    ]
