# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-13 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20160814_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['todo_name']},
        ),
    ]
