# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-10 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0002_auto_20160808_0051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='listid',
        ),
        migrations.RemoveField(
            model_name='item',
            name='cardid',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='userid',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
