# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-15 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repo', '0003_auto_20160810_2025'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
