# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 17:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=100)),
                ('time_raised', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IssueHandle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=7)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='in-progress', max_length=12)),
                ('time_resolved', models.DateTimeField(default=django.utils.timezone.now)),
                ('comments', models.CharField(blank=True, default='', max_length=255)),
                ('is_seen', models.BooleanField(default=False)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_handler', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_handler', to='tracker.Issue')),
            ],
        ),
    ]
