# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20160806_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuehandle',
            name='handler',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='issue_handler', to=settings.AUTH_USER_MODEL),
        ),
    ]
