# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_auto_20160808_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='photo',
        ),
    ]
