# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-07 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_remove_maintenance_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='comments',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
