# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20160808_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainer',
            name='maintenance',
        ),
        migrations.RemoveField(
            model_name='maintainer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Maintainer',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
