# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20160808_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='user',
            field=models.ManyToManyField(default=2, through='tracker.Maintainer', to=settings.AUTH_USER_MODEL),
        ),
    ]
