# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 20:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_auto_20160808_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='user',
        ),
    ]
