# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_remove_maintenance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='approval_status',
            field=models.CharField(blank=True, choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=10, null=True),
        ),
    ]
