# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20160809_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='maintainer',
            field=models.ManyToManyField(blank=True, default=2, related_name='maintainer', to='tracker.Maintainer'),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='maintenance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance', to='tracker.Maintenance'),
        ),
    ]
