# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-09 21:31
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20160809_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintainer',
            name='maintenance',
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='contact',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Phone number must be in the format +123456789 (from 9 to 15 digits).', regex='^\\+?1?\\d{9,15}')]),
        ),
        migrations.AlterField(
            model_name='maintainer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
