# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-02 00:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20160815_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='handler',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='issue_handler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintainer',
            field=models.ManyToManyField(blank=True, default=1, related_name='maintainer', to='tracker.Maintainer'),
        ),
    ]
